### ISSUE TITLE
latest version v1.1 no working

### ISSUE THREAD

**Issue by pipiscrew** [ctmckenna/paywall-ninja#1] opened 2019-11-17 15:38 UTC
hi,

first I tried the latest **v1.1**, no working, tested on browsers :

- Chromium
- Brave

Then I got the v1.0 listed, **tested** on these two browsers **and working**. 

--

Once I drop the v1.1 extension to brave getting the error button (something that is not happening  with v1.0) :
![2019-11-17_173021](https://user-images.githubusercontent.com/3852762/69009679-bdd2da00-094f-11ea-9422-180beb289a9d.png)

![2019-11-17_173035](https://user-images.githubusercontent.com/3852762/69009687-cdeab980-094f-11ea-9b26-f87446f83d78.png)

--

A glitch on v1.0 manifest, written v1.1
![2019-11-17_172915](https://user-images.githubusercontent.com/3852762/69009671-a5fb5600-094f-11ea-8bbd-ae6ead79d2b8.png)

thanks for your time!

[edit]
on v1.1, this [variable](https://github.com/ctmckenna/paywall-ninja/blob/f8d3fa87c61539a8ed605450c958894eb3960d06/paywall-ninja-chrome/disable_js.js#L32) should accept 3 states, because only at wsj needed.

**Comment by ctmckenna** [comment] 2019-11-18 02:42
Hey thanks for submitting this!

My best guess for why this is happening is the extraHeaders option isn't available on your version of Chrome and Brave.  What version of chrome are you running?

Also can you re-try the latest version?  I pushed a fix, but since I can't reproduce it locally (w/ newest version of Brave or Chrome) I'm not sure if it works.

**Comment by pipiscrew** [comment] 2019-11-18 06:05
using an old version

> v0.57.18 based on Chromium: 71

will test it today at evening.

**Comment by pipiscrew** [comment] 2019-11-18 19:37
latest^

is 

working great ;)

tested with all (3) sites.

--

thank you

**Closed** 2019-11-18 21:25 UTC
